[package]
name = "project_ac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
glfw = "0.43.0"
gl = "0.14.0"
